server:
  port: 8181

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

eureka:
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
      defaultZone: ${vcap.services.medileads-queues.credentials.uri:http://medileads-eureka.mybluemix.net}/eureka/
#  instance:
#    hostname: ${vcap.application.uris[0]:localhost}
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#
---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80